#ifndef BARICOIN_CHAINPARAMSSEEDS_H
#define BARICOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the baricoin network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a 16-byte IPv6 address and a port.
 * IPv4 as well as onion addresses are wrapped inside an IPv6 address accordingly.
 */
static SeedSpec6 pnSeed6_main[] = {
    {{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0xff,0xff,0x7d,0xc6,0xe2,0x21}, 8135}
};

static SeedSpec6 pnSeed6_test[] = {
};
#endif // BARICOIN_CHAINPARAMSSEEDS_H
